### ISSUE TITLE
Pretrained model missing

### ISSUE THREAD

**Issue by Sansju** [JianxGao/MinD-3D#1]
Hello, I want to try the inference code, but I can't find the checkpoint path mind3d_sub01.pt or other pretrained models. Could you please tell me where the checkpoints are?Thanks!

**Comment by JianxGao** [comment]
Sorry for forgetting to add the link. You can download the weight of subject 1 through the link: https://drive.google.com/file/d/1ni4g1iCvdpoi2xYtmydr_w3XA5PpNrvm/view?usp=sharing

**Comment by Sansju** [comment]
Thanks!
