### ISSUE TITLE
Missing training code

### ISSUE THREAD

**Issue by thebigeagle** [JianxGao/MinD-3D#2]
Fascinating work and thanks for making the code available.
May I ask when the training script will be released?

**Comment by abm984** [comment]
please help me to run this code assit gives this following error 
Traceback (most recent call last):
  File "/content/MinD-3D/generate_fmri2shape.py", line 5, in <module>
    from src.mind3d import MinD3D
  File "/content/MinD-3D/src/mind3d.py", line 9, in <module>
    from utils import libmcubes
  File "/content/MinD-3D/utils/libmcubes/__init__.py", line 1, in <module>
    from utils.libmcubes.mcubes import (
ModuleNotFoundError: No module named 'utils.libmcubes.mcubes'

**Comment by JianxGao** [comment]
Hi @abm984, you can compile the extension modules via:
`
python setup.py build_ext --inplace
`

**Comment by JianxGao** [comment]
Hi @thebigeagle, I'm in Milan these days. Maybe we can meet offline, and I'll release the script after ECCV.

**Comment by Henrik-hw** [comment]
> 你好@thebigeagle，我最近在米兰，也许我们可以线下见面，ECCV 结束后我会发布剧本。
Hello, is there any plan to make the training code public in the near future?

**Comment by JianxGao** [comment]
Hi, @thebigeagle @Henrik-hw, we have released the traning code.
